# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 14:31
from __future__ import unicode_literals

from django.db import migrations


def create_default_group(apps, schema_editor):
    GroupModel = apps.get_model('auth', 'group')

    group = GroupModel(name='admin')
    group.save()
    group = GroupModel(name='user')
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rucken_todo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_group),
    ]
