# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rucken_todo', '0003_add_permissions_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='todochange',
            name='action',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todochange',
            name='data_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todochange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
