# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rucken_todo', '0004_add_new_fields_to_change_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todochange',
            name='project',
        ),
        migrations.RemoveField(
            model_name='todochange',
            name='task',
        ),
        migrations.AddField(
            model_name='todochange',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
