# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rucken_todo', '0005_add_new_fields_to_change_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todochange',
            old_name='new_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='todochange',
            name='old_data',
        ),
    ]
