# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rucken_todo', '0006_change_fields_on_change_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='todochange',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rucken_todo.TodoProject'),
        ),
    ]
