# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.utils.timezone import now


def create_users(apps, schema_editor):
    UserModel = apps.get_model(settings.AUTH_USER_MODEL)
    GroupModel = apps.get_model('auth', 'group')

    adminGroup = GroupModel.objects.get(name='admin')
    userGroup = GroupModel.objects.get(name='user')

    admin = UserModel()
    admin.username = 'admin'
    admin.email = 'admin@admin.com'
    admin.password = make_password('12345678')
    admin.first_name = 'AdminFirstName'
    admin.last_name = 'AdminLastName'
    admin.is_superuser = False
    admin.is_staff = False
    admin.is_active = True
    admin.date_joined = now()
    admin.save()
    admin.groups.set([adminGroup])

    user1 = UserModel()
    user1.username = 'user1'
    user1.email = 'user1@user1.com'
    user1.password = make_password('12345678')
    user1.first_name = 'User1FirstName'
    user1.last_name = 'User1LastName'
    user1.is_superuser = False
    user1.is_staff = False
    user1.is_active = True
    user1.date_joined = now()
    user1.save()
    user1.groups.set([userGroup])

    user2 = UserModel()
    user2.username = 'user2'
    user2.email = 'user2@user2.com'
    user2.password = make_password('12345678')
    user2.first_name = 'User2FirstName'
    user2.last_name = 'User2LastName'
    user2.is_superuser = False
    user2.is_staff = False
    user2.is_active = True
    user2.date_joined = now()
    user2.save()
    user2.groups.set([userGroup])

    adminGroup.save()
    userGroup.save()


class Migration(migrations.Migration):
    dependencies = [
        ('rucken_todo', '0007_add_project_to_change_model'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
